replicaCount: 1

image:
  repository: your-registory/fe-app
  tag: "0.1.0"
  pullPolicy: ifNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx

  hosts:
    - host: fe.kaayaka.in
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - fe.kaayaka.in
      secretName: frontend-tls

# Optional environment variables
env: {}

# Recommended resource defaults
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
